### ISSUE TITLE
HEIC 파일 첨부 오류

### ISSUE THREAD

**Issue by ekf1121** [kayk1m/img.kay.kr#16]
![image](https://user-images.githubusercontent.com/83440232/160847379-bd6ce946-75e0-4713-a186-91b6dd6db943.png)
![image](https://user-images.githubusercontent.com/83440232/160847451-7d62762c-3e1c-49fa-9d73-81ed70b0e47d.png)

HEIC 파일을 첨부하면 invalid file type 메시지가 나타납니다.
데스크탑 - 크롬

**Comment by blockswords-kay** [comment]
ㄷㄷㄷㄷㄸㄷㄷㄷㄷㄸㄷ

**Comment by ekf1121** [comment]
맥에서만 쓸 수 있남?

**Comment by ekf1121** [comment]
갖다붙이면 포맷 바꿔주는 걸로 이해함 ㅜ
